name: Generate and Update Contribution Snake

on:
  schedule:
    - cron: "0 */4 * * *"  # Executar a cada 4 horas
  workflow_dispatch:  # Permitir execução manual do workflow
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write  # Permissão necessária para fazer push na branch 'output'
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Tempo máximo de execução
    steps:
      # Passo 1: Faz o checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Clona todo o histórico para evitar problemas com branches

      # Passo 2: Gera o arquivo da cobrinha em formato SVG com base nas contribuições do GitHub
      - name: Generate GitHub Contribution Snake Animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}  # Nome do proprietário do repositório
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake-light.svg?palette=github-light
            dist/github-contribution-grid-snake-custom.svg?palette=custom:007bff,ff6600

      # Passo 3: Verifica, cria ou atualiza a branch 'output'
      - name: Create or update output branch
        run: |
          git fetch origin output:output || git checkout -b output

      # Passo 4: Atualiza o README.md com as imagens da cobrinha
      - name: Update README with Snake Animation
        run: |
          echo "## GitHub Contribution Snake" > README.md
          echo "![Snake Animation](https://github.com/${{ github.repository_owner }}/${{ github.repository }}/blob/output/github-contribution-grid-snake.svg)" >> README.md
          echo "![Snake Animation Dark](https://github.com/${{ github.repository_owner }}/${{ github.repository }}/blob/output/github-contribution-grid-snake-dark.svg)" >> README.md
          echo "![Snake Animation Light](https://github.com/${{ github.repository_owner }}/${{ github.repository }}/blob/output/github-contribution-grid-snake-light.svg)" >> README.md
          echo "![Snake Animation Custom](https://github.com/${{ github.repository_owner }}/${{ github.repository }}/blob/output/github-contribution-grid-snake-custom.svg)" >> README.md
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update README with new Snake Animations" || echo "No changes to commit"

      # Passo 5: Faz o push das alterações para a branch 'output'
      - name: Push changes to output branch
        run: |
          git pull origin output --rebase || echo "No changes to pull"
          git push origin output
