name: Generate and Update Contribution Snake

on:
  schedule:
    - cron: "0 */4 * * *"  # Executar a cada 4 horas
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write  # Permissão necessária para fazer push na branch 'output'
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Tempo máximo de execução

    steps:
      # Passo 1: Gera o arquivo da cobrinha em formato SVG com base nas contribuições do GitHub
      - name: Generate GitHub Contribution Snake Animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}  # Nome do proprietário do repositório
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake-light.svg?palette=github-light
            dist/github-contribution-grid-snake-custom.svg?palette=custom:007bff,ff6600

      # Passo 2: Verifica e cria a branch 'output' se ela não existir
      - name: Create output branch if it doesn't exist
        run: |
          git fetch origin
          git checkout -b output || git checkout output

      # Passo 3: Push da animação gerada para a branch 'output'
      - name: Push GitHub Contribution Snake to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Passo 4: Atualiza o README.md para mostrar a imagem da cobrinha
      - name: Update README with Snake Animation
        run: |
          # Atualiza o README.md com as URLs das imagens geradas
          echo "## GitHub Contribution Snake" >> README.md
          echo "![Snake Animation](https://github.com/antoniiocunha/antoniiocunha/blob/output/github-contribution-grid-snake.svg)" >> README.md
          echo "![Snake Animation Dark](https://github.com/antoniiocunha/antoniiocunha/blob/output/github-contribution-grid-snake-dark.svg)" >> README.md
          echo "![Snake Animation Light](https://github.com/antoniiocunha/antoniiocunha/blob/output/github-contribution-grid-snake-light.svg)" >> README.md
          echo "![Snake Animation Custom](https://github.com/antoniiocunha/antoniiocunha/blob/output/github-contribution-grid-snake-custom.svg)" >> README.md
          git add README.md
          git commit -m "Update README with new Snake Animations"
          git push
